using DestallMaterials.CodeGeneration;
using DestallMaterials.WheelProtection.Extensions.Objects;
using DestallMaterials.WheelProtection.Linq;

namespace CodeGenerationTests;

[Parallelizable(scope: ParallelScope.All)]
[TestFixture]
public class FileAddingTests : CodeGenerationTests
{
    [Test]
    public async Task AddFile_Existing_ShouldNotAdd()
    {
        // Arrange
        var system = CodeGenerationWorkspace.Create(_consumerProject);
        var projectName = system.ProjectLocations.Keys.First(pn => pn.Contains("Consumer"));
        var folders = "FolderedItems".ToArrayOfOne();
        
        // Act
        var sourceFile = new CodeFile(new ProjectRelativeFilePath(projectName, folders, "FolderedClass.cs"), sourceText);
        var added = await system.AddSourceFilesAsync(sourceFile.Yield(), default);
        
        // Assert
        Assert.IsEmpty(added);
    }

    [Test]
    public async Task AddFile_New_ShouldAdd()
    {
        // Arrange
        var system = CodeGenerationWorkspace.Create(_consumerProject);
        var projectName = system.ProjectLocations.Keys.First(pn => pn.Contains("Consumer"));

        // Act
        var sourceFile = new CodeFile(new ProjectRelativeFilePath(projectName, "ConsumerModel2.cs"), sourceText);
        var added = await system.AddSourceFilesAsync(sourceFile.Yield(), default);

        // Assert
        Assert.IsNotEmpty(added);
    }

    [Test]
    public async Task AddFile_SameAutogenerated_ShouldNotAdd()
    {
        // Arrange
        var system = CodeGenerationWorkspace.Create(_consumerProject);
        var projectName = system.ProjectLocations.Keys.First(pn => pn.Contains("Consumer"));
        string[] folders = ("Folder1", "Folder2", "LastFolder").ToArray();
        var sourceFile = new CodeFile(new ProjectRelativeFilePath(projectName, folders, "ConsumerModel2.cs"), sourceText);
        await system.AddSourceFilesAsync(sourceFile.Yield(), default);

        // Act
        var sameFile = sourceFile with 
        {

        };
        var added = await system.AddSourceFileAsync(sameFile, default);

        // Assert
        Assert.IsFalse(added);
    }
}