<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
  </ItemGroup>
   
  <ItemGroup>
    <ProjectReference Include="..\..\..\EverModern.Memory\EverModern.Memory.csproj" ReferenceOutputAssembly="true" OutputItemType="Analyzer" />
    <ProjectReference Include="..\SourceGenerator\EverModern.SyntaxGenerator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
