using Microsoft.CodeAnalysis;
using DestallMaterials.WheelProtection.Extensions.Objects;
using DestallMaterials.WheelProtection.Extensions.Tasks;
using Microsoft.CodeAnalysis.CSharp;

namespace DestallMaterials.CodeGeneration;

public static class CodegenWorkspaceExtensions
{
    /// <summary>
    /// Subscribe for particular project changes
    /// </summary>
    /// <param name="codegenSystem">Code generation system</param>
    /// <param name="projectName">Project to whose changes to subscribe</param>
    /// <param name="callback">Callback</param>
    /// <returns>Unsibscription token</returns>
    public static IDisposable SubscribeForProjectChange(this CodeGenerationWorkspace codegenSystem, string projectName, Func<IReadOnlyList<CodeFile>, CancellationToken, Task> callback)
        => codegenSystem.SubscribeForSolutionChange((changes, ct) =>
        {
            var relevantChanges = changes.Where(c => c.Path.ProjectName == projectName).ToArray();
            if (relevantChanges.Length == 0)
            {
                return Task.CompletedTask;
            }
            return callback(relevantChanges, ct);
        });

    /// <summary>
    /// Add one source file to system.
    /// </summary>
    /// <param name="codeGenerationSystem">System</param>
    /// <param name="sourceFile">File to add</param>
    /// <returns>Whether the file has been added or not</returns>
    public static Task<bool> AddSourceFileAsync(this CodeGenerationWorkspace codeGenerationSystem, CodeFile sourceFile, CancellationToken cancellationToken)
        => codeGenerationSystem.AddSourceFilesAsync(sourceFile.Yield(), cancellationToken).Then(files => files.Any());

    /// <summary>
    /// Add a source file to code generation workspace
    /// </summary>
    /// <param name="codeGenerationWorkspace"></param>
    /// <param name="projectName"></param>
    /// <param name="fileName"></param>
    /// <param name="code"></param>
    /// <returns></returns>
    public static Task<bool> AddSourceFileAsync(
        this CodeGenerationWorkspace codeGenerationWorkspace,
        string projectName,
        string fileName,
        string code,
        CancellationToken cancellationToken)
        => codeGenerationWorkspace.AddSourceFileAsync(new CodeFile(new ProjectRelativeFilePath(projectName, fileName), code), cancellationToken);


    /// <summary>
    /// Write physical files to the solution behind the workspace.
    /// </summary>
    /// <param name="codeGenerationWorkspace">Workspace to accept files</param>
    /// <param name="sourceFiles">Files to write</param>
    /// <param name="cancellationToken">Cancellation</param>
    /// <returns>Written file paths</returns>
    public static async Task<IReadOnlyList<string>> WriteFilesAsync(this CodeGenerationWorkspace codeGenerationWorkspace, IEnumerable<CodeFile> sourceFiles, CancellationToken cancellationToken)
    {
        List<string> results = new();
        foreach (var sourceFile in sourceFiles)
        {
            if (sourceFile.Virtual)
            {
                continue;
            }

            var sourceFileToWrite = sourceFile.WithAutogeneratedMark();

            var file = await codeGenerationWorkspace.WriteAsync(sourceFileToWrite, cancellationToken);
            results.Add(file);
        }
        return results;
    }
}
